/* generated by the compiler's C backend; links runtime.a */
#include "runtime.h"

int main(int argc, char **argv){
	runtime_set_args(argc, argv);
	runtime_set_source("demo/getbuiltins.art");
	Env *e = env_new(NULL);
	IR *seq[] = {
		ir_define("builtins1", ir_block((IR*[]){}, 0)),
		ir_define("builtins2", ir_block((IR*[]){}, 0)),
		ir_op("loop", (IR*[]){ir_word("symbols"), ir_block((IR*[]){ir_const(v_token(V_WORD, "k")), ir_const(v_token(V_WORD, "v"))}, 2), ir_seq((IR*[]){ir_op("switch", (IR*[]){ir_call(ir_intrinsic("suffix?"), (IR*[]){ir_load("k"), ir_const(v_str("?"))}, 2), ir_seq((IR*[]){ir_call(ir_intrinsic("append"), (IR*[]){ir_passthrough(v_path((char*[]){"builtins1"}, 1)), ir_call(ir_intrinsic("chop"), (IR*[]){ir_call(ir_intrinsic("to"), (IR*[]){ir_passthrough(v_str(":string")), ir_load("k")}, 2)}, 1)}, 2)}, 1), ir_seq((IR*[]){ir_call(ir_intrinsic("append"), (IR*[]){ir_passthrough(v_path((char*[]){"builtins2"}, 1)), ir_call(ir_intrinsic("to"), (IR*[]){ir_passthrough(v_str(":string")), ir_load("k")}, 2)}, 2)}, 1)}, 3)}, 1)}, 3),
		ir_define("builtins1", ir_call(ir_intrinsic("sort"), (IR*[]){ir_load("builtins1")}, 1)),
		ir_define("builtins2", ir_call(ir_intrinsic("sort"), (IR*[]){ir_call(ir_intrinsic("remove"), (IR*[]){ir_load("builtins2"), ir_block((IR*[]){ir_const(v_str("builtins1")), ir_const(v_str("builtins2"))}, 2)}, 2)}, 1)),
		ir_define("constants", ir_call(ir_intrinsic("filter"), (IR*[]){ir_load("builtins2"), ir_block((IR*[]){ir_const(v_token(V_WORD, "k"))}, 1), ir_block((IR*[]){ir_const(v_token(V_WORD, "function?")), ir_const(v_token(V_WORD, "var")), ir_const(v_token(V_WORD, "k"))}, 3)}, 3)),
		ir_define("builtins2", ir_call(ir_intrinsic("remove"), (IR*[]){ir_load("builtins2"), ir_load("constants")}, 2)),
		ir_call(ir_intrinsic("case"), (IR*[]){ir_call(ir_intrinsic("pathGet"), (IR*[]){ir_word("arg"), ir_const(v_int(0))}, 2), ir_block((IR*[]){ir_const(v_str("1")), ir_const(v_str("->")), ir_const(v_token(V_WORD, "print")), ir_block((IR*[]){ir_const(v_token(V_WORD, "join")), ir_const(v_token(V_ATTRIBUTELABEL, "with")), ir_const(v_str("|")), ir_const(v_token(V_WORD, "builtins1"))}, 4), ir_const(v_str("2")), ir_const(v_str("->")), ir_const(v_token(V_WORD, "print")), ir_block((IR*[]){ir_const(v_token(V_WORD, "join")), ir_const(v_token(V_ATTRIBUTELABEL, "with")), ir_const(v_str("|")), ir_const(v_token(V_WORD, "builtins2"))}, 4), ir_const(v_str("3")), ir_const(v_str("->")), ir_const(v_token(V_WORD, "print")), ir_block((IR*[]){ir_const(v_token(V_WORD, "join")), ir_const(v_token(V_ATTRIBUTELABEL, "with")), ir_const(v_str("|")), ir_const(v_token(V_WORD, "constants"))}, 4)}, 12)}, 2)
	};
	runSeq(e, seq, 8);
	return 0;
}
